---

- hosts: webservers
  tasks:
    - name: sum module
      sum:
        num: 10
      register: sum_result

    - debug: var=sum_result.sum
      when: sum_result.sum > 100
#  roles:
#    - common
#    - webserver

...